apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafe-database
  template:
    metadata:
      name: cafe-database
      labels:
        app: cafe-database
    spec:
      containers:
        - name: cafe-database
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
          image: postgres:latest
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: cafe-database
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  selector:
    app: cafe-database
