apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-cafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakartaee-cafe
  template:
    metadata:
      name: jakartaee-cafe
      labels:
        app: jakartaee-cafe
    spec:
      containers:
        - name: jakartaee-cafe
          env:
            - name: POSTGRES_SERVER
              value: "cafe-database"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          image: localhost:5000/jakartaee-cafe
          ports:
            - containerPort: 9080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9080
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  selector:
    app: jakartaee-cafe
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  selector:
    app: jakartaee-cafe