apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-cafe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jakartaee-cafe
  template:
    metadata:
      name: jakartaee-cafe
      labels:
        app: jakartaee-cafe
    spec:
      containers:
        - name: jakartaee-cafe
          env:
            - name: POSTGRES_SERVER
              value: "db-coffee-demo.postgres.database.azure.com"
            - name: POSTGRES_USER
              value: "jakarta@db-coffee-demo"
            - name: POSTGRES_PASSWORD
              value: "ILoveCafe123!"
          image: acrcoffeedemo.azurecr.io/jakartaee-cafe:v1
          ports:
            - containerPort: 9080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9080
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9080
    - name: https
      port: 443
      targetPort: 9443
  selector:
    app: jakartaee-cafe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jakartaee-cafe
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jakartaee-cafe
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jakartaee-cafe
                port:
                  number: 443
