apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-cafe
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jakartaee-cafe
  template:
    metadata:
      name: jakartaee-cafe
      labels:
        app: jakartaee-cafe
    spec:
      containers:
      - name: jakartaee-cafe
        env:
          - name: POSTGRES_SERVER
            value: "jakartaee-cafe-db-<your suffix>.postgres.database.azure.com"        
          - name: POSTGRES_USER
            value: "postgres@jakartaee-cafe-db-<your suffix>"
          - name: POSTGRES_PASSWORD
            value: "Secret123!"
        image: <your Docker Hub account>/jakartaee-cafe:v2
        ports:
        - containerPort: 9080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1        
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9080
    - name: https
      port: 443
      targetPort: 9443  
  selector:
    app: jakartaee-cafe