global:
  scrape_interval: 5s
  external_labels:
    monitor: 'jakartaee-cafe-monitor'
scrape_configs:
- job_name: 'jakartaee-cafe-metric'
  metrics_path: /metrics/
  static_configs:
  - targets: ['jakartaee-cafe:80']
  scheme: http