global:
  scrape_interval: 5s
  external_labels:
    monitor: 'jakartaee-cafe-monitor'
scrape_configs:
- job_name: 'jakartaee-cafe-metric'
  metrics_path: /metrics/
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - default
    selectors:
    - role: "pod"
      label: "app=jakartaee-cafe"
- job_name: 'quarkus-coffeehouse'
  metrics_path: /q/metrics/
  kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - default
      selectors:
        - role: "pod"
          label: "app=quarkus-coffeehouse"
  scheme: http