apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-cafe
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jakartaee-cafe
  template:
    metadata:
      name: jakartaee-cafe
      labels:
        app: jakartaee-cafe
    spec:
      containers:
      - name: jakartaee-cafe
        env:
          - name: POSTGRES_SERVER
            value: "jakartaee-cafe-db-reza.postgres.database.azure.com"        
          - name: POSTGRES_USER
            value: "postgres@jakartaee-cafe-db-reza"
          - name: POSTGRES_PASSWORD
            value: "Secret123!"
        image: rezarahman/jakartaee-cafe:v4
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9080  
  selector:
    app: jakartaee-cafe
