apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: jakartaee-cafe
spec:
  replicas: 2
  applicationImage: localhost:5000/jakartaee-cafe
  env:
    - name: POSTGRES_SERVER
      value: "cafe-database"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "password"
  service:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 9080
