name: Main Build

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/aks-set-context@v3
        with:
          resource-group: jakartaee-cafe-group-reza
          cluster-name: jakartaee-cafe-cluster-reza      

      - name: Delete Jakarta EE Cafe Deployment
        uses: actions-hub/kubectl@master
        with:
          args: delete -f devops/jakartaee-cafe.yml
        continue-on-error: true
 
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package --file devops/jakartaee-cafe/pom.xml
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: devops
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jakartaee-cafe:v4
                      
      - name: Create Azure Cafe Deployment
        uses: actions-hub/kubectl@master
        with:
          args: create -f devops/jakartaee-cafe.yml
